name: ok_radio_flutter
description: Ok radio mobile app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.7.4+1
  audio_service: ^0.17.0
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

#
#
#
#  fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700


