name: ok_radio_flutter
description: Ok radio mobile app

publish_to: 'none'
version: 1.0.25+25

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

  just_audio: ^0.9.30
  audio_service: ^0.18.8
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  auto_route: ^5.0.4
  flutter_native_splash: ^2.2.16
  get_it: ^7.2.0
  injectable: ^2.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.7
  dropdown_button2: ^1.9.2
  buttons_tabbar: ^1.3.6
  mailto: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  
  
  json_serializable: ^6.5.4
  json_annotation:
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1
  share_plus: ^6.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  lottie: ^2.1.0
  hive_generator: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
  
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: '#ffffff'
  color_dart: '#000000'
  image: 'assets/icons/app_logo.png'
  background_image: 'assets/images/background_screen.png'
  fullscreen: true

  android12: 
    image: 'assets/icons/small_logo.png'
    color: '#FFFFFF'
    icon_background_color: "#FFFFFF"
    image_dark: 'assets/icons/small_logo.png'
    icon_background_color_dark: "#FFFFFF"