name: ok_radio_flutter
description: Ok radio mobile app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter  
  intl: ^0.17.0

  just_audio: ^0.9.27
  audio_service: ^0.18.6
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  fluttertoast: 8.0.8
  cupertino_icons: ^1.0.4
  auto_route: ^4.0.1
  flutter_native_splash: ^2.2.3+1
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  url_launcher: ^6.1.4
  dropdown_button2: ^1.6.3
  buttons_tabbar: ^1.3.6
  mailto: ^2.0.0
  flutter_keyboard_visibility: ^5.3.0
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.6+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.3.1
  json_annotation:
  cached_network_image: ^3.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
   
  flutter_lints: 2.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  lottie: ^1.3.0
  hive_generator: ^1.1.3
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
  
flutter_native_splash:
  android_disable_fullscreen: true
  image: 'assets/icons/ic_app_logo_4.png'
  color_dart: "#000000"
  fullscreen: false
  android: true
  ios: true
  background_image: 'assets/images/ic_app_background.png'
  android_12:
    image:  'assets/icons/ic_app_logo_4.png'

  
  
    




